---
- name: Download /etc/hosts files from remote servers
  hosts: all

  tasks:
    - name: Register output of hosts in hosts_content
      ansible.builtin.command: cat /etc/hosts
      register: hosts_content
      changed_when: hosts_content.rc != 0
      become: true
      become_user: root

    - name: Store /etc/hosts content locally
      ansible.builtin.copy:
        content: "{{ hosts_content.stdout }}"
        dest: tmp/{{ ansible_hostname }}_hosts
        mode: 0644
      delegate_to: localhost
