---
- name: Dump environment variables
  hosts: all
  become: true
  become_user: root
  gather_facts: true
  vars:
    msg: |
      Module Variables ("vars"):
      --------------------------------
      {{ vars | to_nice_json }}
      ================================

      Environment Variables ("environment"):
      --------------------------------
      {{ environment | to_nice_json }}
      ================================

      Group Variables ("groups"):
      --------------------------------
      {{ groups | to_nice_json }}
      ================================

      Host Variables ("hostvars"):
      --------------------------------
      {{ hostvars | to_nice_json }}
      ================================

  tasks:
    - name: Print some debug information
      ansible.builtin.debug:
        msg: "{{ msg.split('\n') }}"
      tags: debug_info
