---
- name: Get NTP time and restart chronyd
  hosts: all
  become: true
  become_user: root
  gather_facts: false

  tasks:
    - name: Stop chronyd service
      ansible.builtin.service:
        name: chronyd
        state: stopped

    - name: Update ntp from external source
      ansible.builtin.command:
        cmd: /usr/sbin/chronyd -q 0.rhel.pool.ntp.org
      register: chronyd_command
      changed_when: chronyd_command.rc == 0
      failed_when: chronyd_command.rc != 0

    - name: Start chronyd service
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: true
