---
- name: Reboot servers
  hosts: all
  become: true
  become_user: root
  gather_facts: false

  tasks:
    - name: Reboot defined server
      ansible.builtin.command:
        cmd: /sbin/shutdown --reboot +1 "Ansible DevOps Warning!!! This machine will be automatically rebooted in 1 minute ..."
      register: reboot_command
      changed_when: reboot_command.rc == 0
      failed_when: reboot_command.rc != 0
