---
- name: Stop firewalls
  hosts: all
  become: true
  become_user: root
  gather_facts: false

  tasks:
    - name: Stop firewalld on defined server
      ansible.builtin.service:
        name: firewalld.service
        state: stopped
        enabled: false
